- name: "Create Zookeeper directories"
  file:
    group: "{{ zookeeper.group }}"
    owner: "{{ zookeeper.user }}"
    path: "{{ item }}"
    recurse: true
    state: directory
  with_items:
    - "{{ zookeeper.data_dir }}"
    - "{{ zookeeper.conf_dir }}"
    - "{{ zookeeper.log_dir }}"

- name: "Copy Zookeeper"
  copy:
    src: "zookeeper-{{ zookeeper.version }}.tar.gz"
    dest: "/usr/local/src/zookeeper-{{ zookeeper.version }}.tar.gz"
    owner: "{{ zookeeper.user }}"

- name: "Unpack Zookeeper"
  unarchive:
    copy: false
    dest: "/usr/local/"
    src: "/usr/local/src/zookeeper-{{ zookeeper.version }}.tar.gz"
    owner: "{{ zookeeper.user }}"

- name: "Rename Zookeeper"
  command: "mv /usr/local/zookeeper-{{ zookeeper.version }} /usr/local/zookeeper" 

- name: "Chown zookeeper "
  file:
    path: "/usr/local/zookeeper"
    owner: "{{ zookeeper.user }}"
    group: "{{ zookeeper.group }}"
    recurse: yes

- name: "Create the Zookeeper systemd environment file"
  template: src="environment.j2" dest="{{ zookeeper.conf_dir }}/environment" owner={{ zookeeper.user }} group={{ zookeeper.group }} mode=0644

- name: "Create the Zookeeper systemd service file"
  template: src="zookeeper.service.j2" dest=/etc/systemd/system/zookeeper.service owner={{ zookeeper.user  }} group={{ zookeeper.group  }} mode=0700



