---
- name: Set program variable to 'resourcemanager'
  set_fact: program="resourcemanager"

- name: Deploy init.d service for datanode
  template: src=hdfs-service.j2 dest=/etc/init.d/hdfs-datanode owner=root group=root mode=0755
  when: ansible_service_mgr != "systemd"

- name: Deploy systemd service for resourcemanger
  template: src=yarn.service.j2 dest=/lib/systemd/system/yarn-resourcemanager.service owner=root group=root mode=0644
  register: resourcemanager_systemd_unit_altered
  when: ansible_service_mgr == "systemd"

# daemon-reload cannot be sent to handler because it is needed before the end of play
# also, we cannot use flush_handlers before the end of play, because we have other handlers
- name: Reload systemd daemon
  command: "systemctl daemon-reload"
  when: ansible_service_mgr == "systemd" and resourcemanager_systemd_unit_altered.changed
  tags:
    - skip_ansible_lint

- name: Register resourcemanger service
  service: name=yarn-resourcemanager enabled=yes
