es_major_version: "6.x"
es_version: "6.2.4"
es_package_url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch"
es_start_service: true
es_restart_on_change: true

es_user: "elasticsearch"
es_group: "elasticsearch"

es_home: "/usr/share/elasticsearch"
default_file: "/etc/sysconfig/elasticsearch"
init_script: "/etc/init.d/elasticsearch"
sysd_script: "/usr/lib/systemd/system/elasticsearch.service"

es_pid_dir: "/var/run/elasticsearch"
es_log_dir: "/var/log/elasticsearch"
es_data_dirs: "/var/lib/elasticsearch"
es_conf_dir: "/etc/elasticsearch"

es_max_open_files: 65536
es_max_threads: "{{ 2048 if ( es_version | version_compare('6.0.0', '<') ) else 8192  }}"
es_max_map_count: 262144

es_heap_size: "16g"
es_jvm_custom_parameters: ''

es_plugins: ["elasticsearch-analysis-ik", "ingest-attachment", "elasticsearch-analysis-pinyin"]
