- name: Yum install keepalived
  yum:
    name: keepalived
    state: present

- name: Enable ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present

- name: Enable ip_nonlocal_bind
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: yes
    state: present

- name: Check if firewalld is running
  shell: systemctl is-active firewalld
  ignore_errors: yes
  register: firewalld_status

- name: Accept vrrp firewall rule (1/3)
  shell: "firewall-cmd --direct --permanent --add-rule ipv4 filter INPUT 0 --in-interface {{ keepalived_interface }} --destination 224.0.0.18 --protocol vrrp -j ACCEPT"
  when: firewalld_status.stdout == "active"
    
- name: Accept vrrp firewall rule (2/3)
  shell: "firewall-cmd --direct --permanent --add-rule ipv4 filter OUTPUT 0 --out-interface {{ keepalived_interface }} --destination 224.0.0.18 --protocol vrrp -j ACCEPT"
  when: firewalld_status.stdout == "active"

- name: Accept vrrp firewall rule (3/3)
  shell: "firewall-cmd --reload"
  when: firewalld_status.stdout == "active"

- name: Copy ngix_check_script in place
  copy:
    src: chk_nginx.sh
    dest: /opt/chk_nginx.sh
    mode: 0755
  
- name: Copy keepalived configuration in place
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify:
    - restart keepalived

- name: Ensure keepalived is started and enabled to start at boot
  service:
    name: keepalived
    state: started
    enabled: yes

