#!/bin/sh
#
# chkconfig: 2345 10 90
# description:  Starts and stops Zabbix Agent using chkconfig

SERVICE="Zabbix agent"
DAEMON=/usr/sbin/zabbix_agentd
PIDFILE=/var/run/zabbix/zabbix_agentd.pid

case $1 in
  'start')
    if [ -x ${DAEMON}  ]
    then
      $DAEMON
      # Error checking here would be good...
      echo "${SERVICE} started."
    else
      echo "Can't find file ${DAEMON}."
      echo "${SERVICE} NOT started."
    fi
  ;;
  'stop')
    if [ -s ${PIDFILE}  ]
    then
      if kill `cat ${PIDFILE}` >/dev/null 2>&1
      then
        echo "${SERVICE} terminated."
        rm -f ${PIDFILE}
      fi
    fi
  ;;
  'restart')
    $0 stop
    sleep 10
    $0 start
  ;;
  *)
    echo "Usage: $0 start|stop|restart"
    ;;
esac

